### ISSUE TITLE
ToolSettings is not displayed

### ISSUE THREAD

**Issue by Josh-Schifter** [iTwin/appui#478]
ToolSettings is not displayed in come iTwin.js sandboxes.  This appears to be a regression that occurred between appui 4.0 and 4.1.3.

The effect is inconsistent.  Some users see ToolSettings and some do not.

We have reproduced the effect in the following sandbox, but it is not limited to this one.
https://www.itwinjs.org/sandboxes/YashodipDeshmukh/Snappable-gltf-decoration
 
In this screenshot, the toolsettings are not displayed:
 
![image](https://github.com/iTwin/appui/assets/38294200/5e4d83f8-0e8c-4c11-9f6a-ba71b7c70fcc)

 
In this screenshot, the toolsettings are displayed:
 
![image](https://github.com/iTwin/appui/assets/38294200/d2309ed7-529d-43f9-b721-f8cad499a376)

 
•	It appears that the cause may be a change that occurred between 4.0 and 4.1.3 versions of the AppUI packages.
•	The problem is NOT isolated to that one sandbox.
•	The problem is NOT isolated to our custom tools.  In an affected session, we also do not see toolsettings for the Select tool.
•	We have reproduced on Chrome, but not all Chrome sessions are affected.
•	We have not been able to reproduce on Edge, but also we’ve done less testing there.

**Comment by aruniverse** [comment]
Should be resolved with [4.3.1](https://github.com/iTwin/appui/releases/tag/release%2F4.3.1)

**Comment by raplemie** [comment]
Hi @Josh-Schifter, we havent released a 4.1.3 patch to AppUI, so I'm unsure of the request. (Is it a mix between core 4.1.3 release, or was it 4.3.1 typo ?) If the version was the core version, we are no longer in lock step with them, and I saw that sanboxes are now using 4.4.0, can you confirm if you still get this issue with 4.4.0, since from our side, this appears to have been fixed in 4.3.1 already.

**Comment by Josh-Schifter** [comment]
@raplemie, I can still reproduce this in multiple sandboxes in PROD.  Use this link (copied from above):
https://www.itwinjs.org/sandboxes/YashodipDeshmukh/Snappable-gltf-decoration
or this one:
https://www.itwinjs.org/sandboxes/iTwinPlatform/PrimitiveTool%20-%20Standard%20ToolSettings

In PROD, sandbox is currently using 4.1.3 of appui-abstract, and 4.4.0 of appui-react.

**Comment by aruniverse** [comment]
> @raplemie, I can still reproduce this in multiple sandboxes in PROD. Use this link (copied from above): [itwinjs.org/sandboxes/YashodipDeshmukh/Snappable-gltf-decoration](https://www.itwinjs.org/sandboxes/YashodipDeshmukh/Snappable-gltf-decoration) or this one: [itwinjs.org/sandboxes/iTwinPlatform/PrimitiveTool%20-%20Standard%20ToolSettings](https://www.itwinjs.org/sandboxes/iTwinPlatform/PrimitiveTool%20-%20Standard%20ToolSettings)
> 
> In PROD, sandbox is currently using 4.1.3 of appui-abstract, and 4.4.0 of appui-react.

you prob need to clean your local storage settings

**Comment by Josh-Schifter** [comment]
@aruniverse, @raplemie, clearing the session cache seems to have fixed it.  How will other users know to do that?  Is there something we should be doing in the sandbox to clear it periodically?

**Comment by aruniverse** [comment]
> @aruniverse, @raplemie, clearing the session cache seems to have fixed it. How will other users know to do that? Is there something we should be doing in the sandbox to clear it periodically?

not ideal, but id recommend running the `RestoreFrontstageLayout` tool anytime the sandbox is opened up https://github.com/iTwin/appui/blob/43958042424fe107ab35d5617eec195e3a6472e8/ui/appui-react/src/appui-react/tools/RestoreLayoutTool.ts#L25

**Comment by raplemie** [comment]
I think one of the issue is that the frontstage is always the same ID between sandboxes, yet change potentially greatly in configuration, so a bogus frontstage would override the stored value of every other sandboxes that do not define a specific name to their frontstages... And I'm not sure how "RestoreFrontstageLayout" tool would be hooked up automatically given that people have control over the Viewer. The most likely solution would be to clean the local storage related keys prior to starting the viewer, so we start fresh each time. Since this is a sandbox, I would assume that Closed/Open widgets and other configuration might be expected to be "clean slate".

**Comment by raplemie** [comment]
Another alternative if we want to keep the safe storage (Or simply ignore it) would be to provide a `UiFramework.setUiStateStorage` and potentially add the sandbox as part of the key when saving the settings, this way, the setting would not be messed up when moving from one sandbox to another, even if they use the same Frontstage Id, which we do not control by the nature of the sandbox.

**Comment by claudiaareneee** [comment]
Hey all! This still seems to be an issue.

The local storage entry for this is `uifw-frontstageSettings.frontstageState[iTwinViewer.DefaultFrontstage]`. Clearing just this variable resets it for me, but from a user perspective this is confusing. 

It's especially confusing because I have my defaultUiConfig specified as so: 
```tsx
defaultUiConfig={
    {
        hideStatusBar: true,
        hideToolSettings: false,
    }
}
```

So I would think the tool settings would show up but they don't. Has any movement been made to fix this bug?

**Comment by GerardasB** [comment]
Closing, since the original issue is supposedly fixed.
